### ISSUE TITLE
Default Values

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/RadialGM#122] opened 2020-05-05 01:56 UTC
This is really odd and occurs on master. For some reason the x and y scale are invalid when loading a GMX, but the x and y value of instances is correct. I can reproduce it loading TKG's Key to Success GMX project. I looked high and low and can't seem to find the source of the bug, the Room proto seems correct and has the correct GMX alias of the field name.

**Comment by RobertBColton** [comment] 2020-05-05 16:33
Ok, not a bug, I was actually loading the GM81, not the GMX. GameMaker 8.1 does not have instance scale at all, or any of the other properties also being complained about, such as color or instance name. What we need then is better defaults.

**Comment by fundies** [comment] 2020-05-05 21:37
duplicate of https://github.com/enigma-dev/enigma-dev/issues/1872

**Closed** 2020-06-01 17:31 UTC
